### ISSUE TITLE
Quick questions

### ISSUE THREAD

**Issue by max-xoo** [Paroxity/portal#47]
Hello I have some questions, I would like to make a "network", composed of a lobby and 4 servers under pocketmine (pm4)
I was suggested to use to be able to navigate between the servers more easily

So I would like to know these little things:

- Is it possible to connect to the proxy on any server from the display of the servers on minecraft and see the connected of the 4 servers counted? 
- If I connect to a server with the xbox live account MaXoooZ in the lobby and I go to server 2, if I use another device with the same account xbox live I can go to server 4?

I think I would have other questions, but I don't have them in mind, I will ask you in the course of this issue
Have a good day to you and thank you in advance.

**Comment by sn3akrr** [comment]
> * Is it possible to connect to the proxy on any server from the display of the servers on minecraft and see the connected of the 4 servers counted?
Yes, the proxy shows the total players connected to each downstream server added together

> * If I connect to a server with the xbox live account MaXoooZ in the lobby and I go to server 2, if I use another device with the same account xbox live I can go to server 4?
No
