### ISSUE TITLE
Instruct Portal to print setup log and a 'readiness message'

### ISSUE THREAD

**Issue by fyradir** [Paroxity/portal#5]
Right now Portal does not print anything during the setup. A 'readiness message' is missing too. It should definitely print something so that users don't think the program is stuck or has crashed. _(I'd also recommend using a structured logger, such as Logrus or Zap, so Portal can give more context to something that is happening)_

**Comment by TwistedAsylumMC** [comment]
Yes we plan on implementing logging soon. The reason we have not done it yet is because we would also like to capture everything being logged and write it to a ``proxy.log`` file for example. We have not had the time to make this yet but we will try soon.

**Comment by TwistedAsylumMC** [comment]
A logger was added in the commit 3ee41e472684016ed0e6ea2c981a95b77bf16b3b, closing this issue now.
